spring:

  application:
    name: klu-certification-platform

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-holy-rain-apg9pcaw-pooler.c-7.us-east-1.aws.neon.tech/CertificationVerificationDB?sslmode=require&channel_binding=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_koXIUMB7Fx1R}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  jackson:
    serialization:
      write-dates-as-timestamps: false

    time-zone: Asia/Kolkata

server:
  port: 8080

  servlet:
    context-path: /api

socketio:
  host: 0.0.0.0
  port: 9092

logging:
  level:
    org.springframework: INFO